### ISSUE TITLE
Issues Loading in PaperMC

### ISSUE THREAD

**Issue by matthew119427** [Codeski/dynmap-structures#72]
I'm using Paper vgit-Paper-499 on MC v1.19.4 and I'm getting this error when attempting to load the plugin on startup:

```
[20:22:11 ERROR]: Error occurred while enabling dynmap-structures v2.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.BIOMES[org.bukkit.block.Biome.ordinal()]" is null
```

**Comment by AmonBune** [comment]
I have the same issue. Here is the full call stack:

```
[18:16:38] [Server thread/INFO]: [dynmap-structures] Enabling dynmap-structures v2.6.0
[18:16:38] [Server thread/ERROR]: Error occurred while enabling dynmap-structures v2.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.BIOMES[org.bukkit.block.Biome.ordinal()]" is null
        at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.onEnable(DynmapStructuresPlugin.java:552) ~[DynmapStructures.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-514]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-514]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-514]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-514]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[18:16:38] [Server thread/INFO]: [dynmap-structures] Disabling dynmap-structures v2.6.0
```

**Comment by PKMWM1** [comment]
Anu update on this? Is this an issue with running 1.19.4? Is there any fix known?

**Comment by knitemares** [comment]
I'm having the same issue

**Comment by IxeYgrek** [comment]
Hi,

Same error for me : 
Paper 1.19.4-550
Plugin v2.6.0

Logs :  

[15:16:47] [Server thread/INFO]: [dynmap-structures] Enabling dynmap-structures v2.6.0
[15:16:47] [Server thread/ERROR]: Error occurred while enabling dynmap-structures v2.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.BIOMES[org.bukkit.block.Biome.ordinal()]" is null
	at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin.onEnable(DynmapStructuresPlugin.java:552) ~[DynmapStructures-2.6.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Pezmc** [comment]
Fix is in #77
